apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: arah24/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: arah24/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/*.js'
            dest: .
    - image: arah24/bus
      context: bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/*.js'
            dest: .
    - image: arah24/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/*.js'
            dest: .
    - image: arah24/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/*.js'
            dest: .
    - image: arah24/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/*.js'
            dest: .
